version: "3.9"

services:
    web:
        build: .
        command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/src/staticfiles
        expose:
            - 8000
        depends_on:
            - postgredb
    postgredb:
        image: postgres:13.0-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./logs:/var/log
        environment:
            POSTGRES_DB: "netology_stocks_products"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"

    nginx:
        build: ./nginx
        volumes:
            - static_volume:/src/staticfiles
        ports:
            - 1337:80
        depends_on:
            - web
volumes:
    pgdata:
    static_volume:
